name: Test
on: push

env:
  NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN: ${{secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN}}
  NEXT_PUBLIC_CONTENTFUL_SPACE_ID: ${{secrets.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}}

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Context
        run: |
        echo ${{env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN}}
        echo ${{env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID}}
